export const arrTopics = [
  "COVID-19",
  "Language",
  "Movies",
  "Pets",
  "Nature",
  "Adventure",
  "Climate",
  "Handicraft",
  "Writing",
  "Beauty",
  "Makeup",
  "Fitness",
  "Cosplay",
  "Dancing",
  "Singing",
  "Astrology",
  "Gardening",
  "Collecting",
  "Aviation",
  "Shopping",
  "Design",
  "Technology",
  "Music",
  "Gaming",
  "Fashion",
  "Cars",
  "Architecture",
  "Television",
  "Travel",
  "Photography",
  "Fiction",
  "Reading",
  "Sports",
  "Cooking",
  "Food",
  "Business",
  "Investing",
  "Economics",
  "Finance",
  "Startup",
  "Career",
  "Ideas",
  "Future",
  "Space",
  "New",
  "Age",
  "Politics",
  "Culture",
  "Art",
  "Feminism",
  "Life",
  "Casual",
  "Religion",
  "Psychology",
  "Humor",
  "Health",
  "Depression",
  "History",
  "Education",
  "School",
  "Life",
  "Science",
  "Family",
  "Parenting",
  "Sex",
  "LGBTQ+",
  "Relationships",
  "Poetry",
  "Vegan",
  "Anime",
  "Philosophy",
  "Magic",
  "Storytelling",
  "News",
  "Law",
  "Sustainability",
  "Sci-Fi",
  "Deaf",
  "Coding",
  "Fantasy",
  "DIY",
  "Board",
  "Games",
  "Environment",
  "Illustration",
  "Archeology",
  "Theatre",
  "Wine",
  "Farming",
  "Theme",
  "Parks",
  "Disabilities",
  "Origami",
  "Martial",
  "Arts",
  "Museums",
];

// export const topicsFilterData = [
//   { Interest: "COVID-19" },
//   { Interest: "Language" },
//   { Interest: "Movies" },
//   { Interest: "Pets" },
//   { Interest: "Nature" },
//   { Interest: "Adventure" },
//   { Interest: "Climate" },
//   { Interest: "Handicraft" },
//   { Interest: "Writing" },
//   { Interest: "Beauty" },
//   { Interest: "Makeup" },
//   { Interest: "Fitness" },
//   { Interest: "Cosplay" },
//   { Interest: "Dancing" },
//   { Interest: "Singing" },
//   { Interest: "Astrology" },
//   { Interest: "Gardening" },
//   { Interest: "Collecting" },
//   { Interest: "Aviation" },
//   { Interest: "Shopping" },
//   { Interest: "Design" },
//   { Interest: "Technology" },
//   { Interest: "Music" },
//   { Interest: "Gaming" },
//   { Interest: "Fashion" },
//   { Interest: "Cars" },
//   { Interest: "Architecture" },
//   { Interest: "Television" },
//   { Interest: "Travel" },
//   { Interest: "Photography" },
//   { Interest: "Fiction" },
//   { Interest: "Reading" },
//   { Interest: "Sports" },
//   { Interest: "Cooking" },
//   { Interest: "Food" },
//   { Interest: "Business" },
//   { Interest: "Investing" },
//   { Interest: "Economics" },
//   { Interest: "Finance" },
//   { Interest: "Startup" },
//   { Interest: "Career" },
//   { Interest: "Ideas" },
//   { Interest: "Future" },
//   { Interest: "Space" },
//   { Interest: "New" },
//   { Interest: "Age" },
//   { Interest: "Politics" },
//   { Interest: "Culture" },
//   { Interest: "Art" },
//   { Interest: "Feminism" },
//   { Interest: "Life" },
//   { Interest: "Casual" },
//   { Interest: "Religion" },
//   { Interest: "Psychology" },
//   { Interest: "Humor" },
//   { Interest: "Health" },
//   { Interest: "Depression" },
//   { Interest: "History" },
//   { Interest: "Education" },
//   { Interest: "School" },
//   { Interest: "Life" },
//   { Interest: "Science" },
//   { Interest: "Family" },
//   { Interest: "Parenting" },
//   { Interest: "Sex" },
//   { Interest: "LGBTQ+" },
//   { Interest: "Relationships" },
//   { Interest: "Poetry" },
//   { Interest: "Vegan" },
//   { Interest: "Anime" },
//   { Interest: "Philosophy" },
//   { Interest: "Magic" },
//   { Interest: "Storytelling" },
//   { Interest: "News" },
//   { Interest: "Law" },
//   { Interest: "Sustainability" },
//   { Interest: "Sci-Fi" },
//   { Interest: "Deaf" },
//   { Interest: "Coding" },
//   { Interest: "Fantasy" },
//   { Interest: "DIY" },
//   { Interest: "Board" },
//   { Interest: "Games" },
//   { Interest: "Environment" },
//   { Interest: "Illustration" },
//   { Interest: "Archeology" },
//   { Interest: "Theatre" },
//   { Interest: "Wine" },
//   { Interest: "Farming" },
//   { Interest: "Theme" },
//   { Interest: "Parks" },
//   { Interest: "Disabilities" },
//   { Interest: "Origami" },
//   { Interest: "Martial" },
//   { Interest: "Arts" },
//   { Interest: "Museums" },
// ];

export const arrLanguages = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Asturian",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Cebuano",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Church",
  "Slavic",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Dari",
  "Divehi",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Filipino",
  "Finnish",
  "Flemish",
  "French",
  "Fulah",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek",
  "Guarani",
  "Gujarati",
  "Haitian",
  "Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri",
  "Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Jamaican",
  "Patois",
  "Japanese",
  "Javanese",
  "Kabyle",
  "Kalaallisut",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu",
  "Kinyarwanda",
  "Kirghiz",
  "KomiKongo",
  "Korean",
  "Kuanyama",
  "Kurdish",
  "Lao",
  "Latin",
  "Latvian",
  "Limburgish",
  "Lingala",
  "Lithuanian",
  "Lojban",
  "Luba-Katanga",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Moldavian",
  "Mongolian",
  "Nauru",
  "Navajo",
  "Ndonga",
  "Nepali",
  "North",
  "Ndebele",
  "Northern",
  "Sami",
  "Occitan",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Ossetian",
  "Pali",
  "Panjabi",
  "Persian",
  "Polish",
  "Portuguese",
  "Pushto",
  "Quechua",
  "Romani",
  "Romanian",
  "Romansh",
  "Rundi",
  "Russian",
  "Rusyn",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Santali",
  "Sardinian",
  "Scottish",
  "Gaelic",
  "Serbian",
  "Serbo-Croatian",
  "Shona",
  "Sichuan-Yi",
  "Sicilian",
  "Sindhi",
  "Sinhalese",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho",
  "South-Ndebele",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "TwiUkrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
];

export const ageGroup = ["14-18", "19-25", "26-35", "36-40", "40-56", "56+"];
